package com.mysql.qi_fu.librarymanage.sql.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.mysql.qi_fu.librarymanage.sql.BookEntity;
import com.mysql.qi_fu.librarymanage.sql.Cord;
import com.mysql.qi_fu.librarymanage.sql.Message;
import com.mysql.qi_fu.librarymanage.sql.User;

import com.mysql.qi_fu.librarymanage.sql.greendao.BookEntityDao;
import com.mysql.qi_fu.librarymanage.sql.greendao.CordDao;
import com.mysql.qi_fu.librarymanage.sql.greendao.MessageDao;
import com.mysql.qi_fu.librarymanage.sql.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookEntityDaoConfig;
    private final DaoConfig cordDaoConfig;
    private final DaoConfig messageDaoConfig;
    private final DaoConfig userDaoConfig;

    private final BookEntityDao bookEntityDao;
    private final CordDao cordDao;
    private final MessageDao messageDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookEntityDaoConfig = daoConfigMap.get(BookEntityDao.class).clone();
        bookEntityDaoConfig.initIdentityScope(type);

        cordDaoConfig = daoConfigMap.get(CordDao.class).clone();
        cordDaoConfig.initIdentityScope(type);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        bookEntityDao = new BookEntityDao(bookEntityDaoConfig, this);
        cordDao = new CordDao(cordDaoConfig, this);
        messageDao = new MessageDao(messageDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(BookEntity.class, bookEntityDao);
        registerDao(Cord.class, cordDao);
        registerDao(Message.class, messageDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        bookEntityDaoConfig.clearIdentityScope();
        cordDaoConfig.clearIdentityScope();
        messageDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public BookEntityDao getBookEntityDao() {
        return bookEntityDao;
    }

    public CordDao getCordDao() {
        return cordDao;
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
